#pragma once

#include "core/EventLoop.h"
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <string_view>
#include <vector>

namespace aegon::http::tls {

class TlsStream {
public:
    TlsStream(core::EventLoop& loop, int client_fd, SSL_CTX* ctx);
    ~TlsStream();

    TlsStream(const TlsStream&) = delete;
    TlsStream& operator=(const TlsStream&) = delete;

    /**
     * @brief Perform async TLS handshake over io_uring.
     * @return true if handshake completed successfully, false on error/disconnect.
     */
    core::Task<bool> handshake();

    /**
     * @brief Read decrypted application plaintext from the TLS connection.
     */
    core::Task<int> read_plaintext(void* buf, size_t max_len);

    /**
     * @brief Encrypt and transmit application plaintext over io_uring.
     */
    core::Task<int> write_plaintext(const void* buf, size_t len);

    /**
     * @brief Negotiated ALPN protocol (e.g. "h2", "http/1.1", or empty).
     */
    [[nodiscard]] std::string_view alpn() const noexcept;

    [[nodiscard]] bool is_h2() const noexcept { return alpn() == "h2"; }

private:
    core::Task<bool> flush_outbound();

    core::EventLoop& loop_;
    int client_fd_;
    SSL* ssl_{nullptr};
    BIO* in_bio_{nullptr};   // Ciphertext received from network -> read by SSL
    BIO* out_bio_{nullptr};  // Ciphertext generated by SSL -> sent to network
    bool handshake_done_{false};
};

} // namespace aegon::http::tls
